### ISSUE TITLE
不要脸的开源

### ISSUE THREAD

**Issue by zhanglianzhong** [mn3711698/singlecoin#1]
要脸吗?还开源,核心的东西全部封闭,有脸说开源?还不是想收费,要么不开源,要开源就正儿八经的开源.这种还开源最无耻

**Comment by 1272339173** [comment]
联系方式给一个啊

**Comment by mn3711698** [comment]
> 联系方式给一个啊

代码上写有，说明下边也能联系到。

**Comment by mn3711698** [comment]
从来没打开开源，这只是作为一个存放代码的地方
